### PR TITLE
Minor changes and improvements

### PR DESCRIPTION
**Pull request by AndriiHarashchak**
In this pull request I add the ability to set a custom label for yAxis (still use units[index] if not provided). Fix exception when DateTime in series is the same for all values in Map(offset in NaN exception). Update example app to remove deprecated FlatButton and add windows support (tested on my windows 11 pc).

### CODE REVIEW

**Comment by thembangpa** [comment]
Hi @AndriiHarashchak 

I see that after the recent changes(commit sha -  **716346ed4c0a39e15ee1817de41be5e0b43cfd93**), the chart shows extra lines in the graph: 
ExtraLine_Chart

But on loading again, the chart shows up fine like shown in the image below:
ProperLineChart

Do you know why is it doing that? Have you seen that as well? 

Regards
Tashi

**Comment by AndriiHarashchak** [comment]
Hi @tashiwangdi.
Yes. I also saw this. I`m not sure why this thing happens, but it connected with a fix for the "offset is NaN" error. As I saw, this thing occurs only when a chart is resized.
 I suppose to fix this issue offset counting algorithm should be improved to not calculate this "NaN" value, cause my fix only changes NaN to 0 for offset (x offset if I am correct). And  we can see this on your screenshot.

**Comment by thembangpa** [comment]
Thanks @AndriiHarashchak  for your reply. Yes, this issue occurs if I open the chart in landscape mode. The portrait mode does not display this behavior.

**Comment by tashiwangdi** [comment]
Hi @AndriiHarashchak 
Did you get a chance to run tests and update golden snapshots when you made the fix ? 

Regards

**Pull request merged**
